#!/usr/bin/env python3
""" covid19-vi  -  Visualization utilities for the COVID-19 data from Johns Hopkins.

    Copyright (C) 2020  Natalya Langford

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
__author__ = 'Natalya Langford'
__copyright__ = 'Copyright (C) 2020 Natalya Langford'
__credits__ = ['']
__license__ = 'GNU General Public License'
__program_name__ = 'covid19-vi'
__version__ = 'v0.0.1'
__maintainer__ = 'Natalya Langford'
__status__ = 'Under Development'
__docformat__ = 'reStructuredText'
# pylint: disable=multiple-statements
# pylint: disable=line-too-long

import argparse
import sys
import os
from datetime import datetime
import shutil
import csv
import pickle
import urllib.request
import pandas as pd


class CovidData:
    _covid_data = {'confirmed': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv',
                   'deaths': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv',
                   'recoveries': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv'}
    _pickle_filename = 'covid_data.pickle'

    def __init__(self, download=False):
        """
        :type download: Bool
        :param download:
        :return None
        """
        self.data = {'download_date': None, 'confirmed': None, 'deaths': None, 'recoveries': None}
        self.read_datafile(download=download)

    def print_sources(self):
        """
        :return: None
        """
        [print('{}: {}'.format(k, v)) for k, v in self._covid_data.items()]

    def read_datafile(self, download=False):
        """

        :param download:
        :type download: Bool
        :return: Bool
        """
        """ Return the new downloaded data's filename as a string
            Source: https://github.com/Ricks-Lab/amdgpu-utils/blob/c10dba61f11b9e5fb44d24acd1fa74122668afc2/GPUmodules/PCImodule.py
        """
        if not download and os.path.isfile(self._pickle_filename):
            # Read pickle file.
            with open(self._pickle_filename, 'rb') as f:
                self.data = pickle.load(f)
            return True

        for report_key in self._covid_data.keys():
            temp_file_name = 'covid_{}_{}.csv'.format(report_key, datetime.utcnow().strftime('%m%d_%H%M%S'))  #go over this for loop, a bit confusing
            with urllib.request.urlopen(self._covid_data[report_key]) as response, open(temp_file_name, 'wb') as out_file:
                shutil.copyfileobj(response, out_file)
            self.data[report_key] = self.read_csv_file(temp_file_name)

        with open(self._pickle_filename, 'wb') as f:
            pickle.dump(self.data, f)

        return True

    @staticmethod
    def read_csv_file(file_name):
        """

        :param file_name:
        :return: list
        """
        df = pd.read_csv(file_name)
        df['total'] = df.values[:, -1]
        return df

    def top_ten(self, report_key='confirmed'):
        """

        :param report_key:
        :type report_key: string
        :return: None
        """
        ttdf = self.data[report_key].sort_values(['total'], ascending=False).head(30) #what does ascending and head(30) do
        print(ttdf)

    def top_ten_us_states(self, report_key='confirmed'):
        """

        :param report_key:
        :type report_key: string
        :return:
        """
        ldf = self.data[report_key].loc[self.data[report_key]['Country/Region'] == 'US']
        ttdf = ldf.sort_values(['total'], ascending=False).head(30)
        print(ttdf)


def main():
    """
    Main flow for covid19-vi.
    :return: None
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--about', help='README',
                        action='store_true', default=False)
    parser.add_argument('--parameter', help='confirmed, deaths, recoveries',
                        type=str, default='confirmed')
    parser.add_argument('--download', help='download csv file',
                        action='store_true', default=False)
    parser.add_argument('--filename', help='csv file name',
                        type=str, default='')
    parser.add_argument('--table', help='Output table of basic GPU details',
                        action='store_true', default=False)
    parser.add_argument('-d', '--debug', help='Debug output',
                        action='store_true', default=False)
    args = parser.parse_args()

    # About me
    if args.about:
        print(__doc__)
        print('Author: ', __author__)
        print('Copyright: ', __copyright__)
        print('Credits: ', __credits__)
        print('License: ', __license__)
        print('Version: ', __version__)
        print('Maintainer: ', __maintainer__)
        print('Status: ', __status__)
        sys.exit(0)

    covid_data = CovidData(download=args.download)

    covid_data.top_ten()

    covid_data.top_ten_us_states()

    sys.exit(0)


if __name__ == '__main__':
    main()
